package WebDriverTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class ClickOnceTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void clickOnce() {
        driver.get("http://localhost/");
        driver.findElement(By.linkText("Click me baby")).click();
        driver.findElement(By.id("clickMe")).click();
        driver.findElement(By.id("clickMe")).click();
        assertThat(driver.findElement(By.id("clicks")).getText(), is("2"));
        assertThat(driver.findElement(By.cssSelector(".description")).getText(), is("kliky"));
    }

    @Test
    public void cssSelectorTest(){
        driver.get("http://localhost/");
        driver.findElement(By.linkText("Click me baby")).click();
        driver.findElement(By.cssSelector("div.container button")).click();
        assertThat(driver.findElement(By.id("clicks")).getText(), is("1"));
    }
}
